/* Uncomment below script on mysql */

/* DROP schema IF EXISTS `jpa_jbd`;

CREATE schema IF NOT EXISTS `jpa_jbd`;
use `jpa_jbd`; */


DROP TABLE IF EXISTS `USER_CREDENTIALS`;
DROP TABLE IF EXISTS `USER_DETAILS`;
DROP TABLE IF EXISTS `ADDRESS`;
DROP TABLE IF EXISTS `CUSTOMER`;

CREATE TABLE `USER_DETAILS` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`CREATED_TIME` datetime NOT NULL,
	`UPDATED_TIME` datetime DEFAULT NULL,
	`USER_TYPE` varchar(45) NOT NULL,
	`DOB` date NOT NULL,
	 PRIMARY KEY (`ID`)
);

CREATE TABLE `USER_CREDENTIALS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(20) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
   `USER_DETAIL` INT NOT NULL,
   UNIQUE (`USER_NAME`),
   PRIMARY KEY (`ID`),
    CONSTRAINT `UD_CREDS_ID_FK` 
     FOREIGN KEY (`USER_DETAIL`) REFERENCES `USER_DETAILS` (`ID`)
   
);


CREATE TABLE `CUSTOMER` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NAME` varchar(45) NOT NULL,
	`MEMBERSHIP` varchar(100) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `ADDRESS` (
  `CUSTOMER` INT NOT NULL,
  `BUILDING` VARCHAR(45) NOT NULL,
  `STREET` VARCHAR(100) NOT NULL,
  `STATE` VARCHAR(45) NOT NULL,
  `COUNTRY` VARCHAR(45) NOT NULL,
  `ZIPCODE` VARCHAR(45) NOT NULL,
   CONSTRAINT `BK_PUB_ID_FK` 
     FOREIGN KEY (`CUSTOMER`) REFERENCES `CUSTOMER` (`ID`)
);

	
     
